name: nasarover
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  json_annotation: ^4.4.0
  http: ^0.13.4
  flutter_html: ^2.2.1
  dropdown_button2: ^1.4.0
  flutter_facebook_auth: ^4.4.1+1
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
  - assets/images/

  


